version: "3.8"

services:
  frontend:
    container_name: user_controller_frontend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    networks:
      - user-controller-network
volumes:
  node_modules:

networks:
  user-controller-network:
    name: user-controller-network
    driver: bridge
